version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - network1
  web:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - mongo

volumes:
  mongodata:

networks:
  network1: